set_property SRC_FILE_INFO {cfile:{C:/Users/Alex/Desktop/EE 316/Labs/Lab_4/lab4.1.1/project_1/project_1.srcs/constrs_1/imports/new/constraint1.xdc} rfile:../../../project_1.srcs/constrs_1/imports/new/constraint1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports {call}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {cancel}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {light}]
